analytics: {}
color:
  brandColors:
    - '#C8C8C8'
    - '#000000'
    - '#807878'
    - '#000000'
    - '#000000'
  brandStrength: 0.780392
  lightness: 0.340957
  rhythmicContrast: 0.761951
  saturation: 0.541225
cta: {}
layout_spectrum: 0.578383
name: ninefivethreeone
opengraph: {}
purpose: {}
typography_spectrum: 0.3842539545497372
